image:
  file: .gitpod.dockerfile
ports:
- port: 9080
- port: 3306
- port: 8080
tasks:
- name: initAndStartServers  #- means terminal
  command: >
    cp .env.example .env;
    bash $GITPOD_REPO_ROOT/podConfs/startup.sh;
    gp preview $(gp url 9080)/phpmyadmin;
    gp preview $(gp url 8080);
  init: echo "I am init executed before command"
- name: Terminal
  command: >
    echo "Welcome!";
    echo "";
    echo "Start, stop or review Apache errors:";
    echo " * apachectl stop";
    echo " * apachectl start";
    echo " * gp open /var/log/apache2/access.log";
    echo " * gp open /var/log/apache2/error.log";
    echo " * mysql user: devuser password: 1 ";
